# Set the language
language: objective-c

# Build with Xcode 8 to ensure Swift 3 is used
osx_image: xcode8
# xcode_project: ContactsDemo.xcodeproj
xcode_scheme: ContactsDemo
# xcode_sdk: iphonesimulator10.0

env:
    global:
        - LANG=en_US.UTF-8

        - PROJECT="ContactsDemo.xcodeproj"
        - IOS_SCHEME="ContactsDemo"

        - IOS_SDK=iphonesimulator10.0

    matrix:
        - DESTINATION="OS=9.0,name=iPhone 6 Plus"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="NO"
        - DESTINATION="OS=9.1,name=iPhone 6s"      SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="NO"
        - DESTINATION="OS=9.2,name=iPhone 6s Plus" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="NO"
        - DESTINATION="OS=10.0,name=iPhone 7" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="NO"

script:
- if [ $RUN_TESTS == "YES" ]; then
        xcodebuild test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  else
        xcodebuild clean build -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  fi
